tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'git'
brew "go"
brew 'ghq'
brew 'gibo'
brew "heroku/brew/heroku"
brew 'jq'
brew 'openssl'
brew 'sqlite'
brew 'mas'
brew "nkf"
brew 'peco'
brew 'fzf'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'fish'

cask 'alfred'
cask 'bettertouchtool'
cask 'docker'
cask 'iterm2'
cask 'visual-studio-code'

# mas 'Xcode', id: 497799835
# mas 'Keynote', id: 409183694
# mas 'ASUS Device Discovery', id: 995124504
# mas 'Display Menu', id: 549083868
# mas 'CompareMerge', id: 478570084
